### ISSUE TITLE
add some sort of campaign support? 

### ISSUE THREAD

**Issue by CatzHoekk** [drekdrek/grinding-stats#1]
It would be cool to if the plugin would track the overall grind on a campaign too. 

https://trackmania.io/api/campaigns/0 will return the official ones + extra so that´s relatively easy to get for the foreseeable future. If you want to implement other campaigns via the api, not my decision. 

Maybe other custom campaigns could be added manually using the id? 

Maybe you would add a flag or campaignid to the json so yo can quickly recognize if a map is part of a campaign to avoid extensive loops. (watch out: maps can be part of several campaigns)

Idk if the time should be part of the hud but it would be cool if it was accessible via the Openplanet drop down menuu or so.

**Comment by drekdrek** [comment]
I am about to travel for the next two days, but I will see about getting this done. thank you for the idea :)

**Comment by drekdrek** [comment]
getting worked on in current big update
![screenshot](https://drek.cc/i/raw/Cs23d2Qp.png)

**Comment by drekdrek** [comment]
added in b7a8c522143bf80fcb1313d69afb49ad75f456d1
will be released soon
