### ISSUE TITLE
Grinding stats no longer works for TM2 after most recent update.

### ISSUE THREAD

**Issue by MrTrolyMoly** [drekdrek/grinding-stats#11]
I updated this plugin to 2.0.0 and it came back with a script error. I am on OP v1.23.5 (most recent)
![image](https://user-images.githubusercontent.com/49452999/176324909-5a79aee1-9409-4430-9e6c-501e6a496846.png)

**Comment by drekdrek** [comment]
i'll put in a fix right away

**Comment by drekdrek** [comment]
should be on the plugin manager now
