### ISSUE TITLE
Getting the map name from its file name?

### ISSUE THREAD

**Issue by Richard-Degenne** [drekdrek/grinding-stats#13]
Hi!

Is there an easy way to reconcile a JSON file from the "Grinding Stats" folder to the map it belongs to?

While browsing the code (I am not an ActionScript developer), I assume [this line](https://github.com/drekdrek/grinding-stats/blob/main/Grinding%20Stats.as#L86) is responsible for naming the file using the map's `IdName`?

**Comment by drekdrek** [comment]
the file is stored as the *mapid*.Jason, there isn't that easy of a way to get the name of the map from the I'd that I know of.

**Comment by Richard-Degenne** [comment]
Is the mapId only a value that's internal to Trackmania? Or can I find it on third-party apps like TMX or Trackmania.io?

**Comment by drekdrek** [comment]
it is used on TM.io, but i dont think it is used on tmx
im sure theres a way to use nadeo's api to get information from the mapid, but i dont know how exactly to do it.
to get the trackmania.io page for the track, just append it to this url `https://trackmania.io/#/leaderboard/`
