### ISSUE TITLE
Reset counter updated even though finish is incremented

### ISSUE THREAD

**Issue by hsiddique** [drekdrek/grinding-stats#17]
When I finish a track, the counter for finishes is incremented by one,then when the menu appears and I select "Improve" the reset counter is incremented by one.

**Comment by drekdrek** [comment]
the reset counter is more like the number of attempts on a track than resets

**Comment by hsiddique** [comment]
Got it.
Would it be worth renaming Resets to Attempts. As that is a better reflection of the actual counter.




________________________________
