### ISSUE TITLE
Implausible/Incorrect Total & Session time

### ISSUE THREAD

**Issue by CatzHoekk** [drekdrek/grinding-stats#19]
[Discord chat link](https://discord.com/channels/@me/1065612327023546398/1065612393977221190)

In my session today i played about 2 hours and when i chcked grindingstats (it only shows when i press F3) i saw it only showed 50 seconds for total time and session time. 

I literally showed Total time: 0:00:55, 287 resets, 17 finishes at some point.

The logfile shows that it`s implausible. 

In line 237 at 09:54:12 Splitspeeds logs that it enters a new map, 6xEcwWkjpitcDpQ2jIbEXTya7hk
In line 367 at 12:06:07 Grindingstats writes finishes 17 resets 286 time 97281 respawns 15

Here's the json after the session
[6xEcwWkjpitcDpQ2jIbEXTya7hk.json](https://github.com/drekdrek/grinding-stats/files/10457638/6xEcwWkjpitcDpQ2jIbEXTya7hk.json.txt)

And that's the whole OP log file
[grindingstats-log.txt](https://github.com/drekdrek/grinding-stats/files/10457580/grindingstats-log.txt)

**Comment by CatzHoekk** [comment]
I believe i got it. Typical. Once you report the bug you also find the cause moments later.

The timer doesn't seem to start when grindingstats is only showing when the Openplanet menu is open. All other values update properly but the timer doesn`t seem to start ever. 

After i knew that i checked the json files of my recently played maps and found a lot of maps where the time is 0.

Here are some examples from my last couple game session. 

[wJ9vGLCLpBOjpy2KompdetPMjEa.json.txt](https://github.com/drekdrek/grinding-stats/files/10457867/wJ9vGLCLpBOjpy2KompdetPMjEa.json.txt)
[WNc0aFG2P7TswituP3VEw41xtI0.json.txt](https://github.com/drekdrek/grinding-stats/files/10457868/WNc0aFG2P7TswituP3VEw41xtI0.json.txt)
[Rg9njLSXYX3hSPQEcPZ_ewrtv53.json.txt](https://github.com/drekdrek/grinding-stats/files/10457869/Rg9njLSXYX3hSPQEcPZ_ewrtv53.json.txt)

**Comment by drekdrek** [comment]
should be fixed in eac37a9a6358eaa1d073c3aec459a034afd5f3ed
i am unable to test until later today, i will close this issue when i am 100% able to confirm it fixed the problem.

**Comment by drekdrek** [comment]
ive submitted it to openplanet for review
