### ISSUE TITLE
Blank sessions stats when playing a map for the first time

### ISSUE THREAD

**Issue by Eggerd** [drekdrek/grinding-stats#20]
This started with version 2.0.9, currently using the latest version (2.0.10).

When playing a map for the very first time, the `Session Finishes` and `Session Resets` are just blank and stay that way for the whole time. They only appear after reloading the map and only if there actually was a reset or finish during the previous session. Otherwise, the respective stat stays blank.

If `Show Duplicates` is enabled, the stats are displayed normally. So it seems like they are only blank while the session stat equals the total stat.

| `Show Duplicates` disabled | `Show Duplicates` enabled |
| --- | --- |
| ![stats_missing_no_dup](https://user-images.githubusercontent.com/904567/214362927-64cd06ef-d923-45df-8e1a-6a23b1b2fa7c.png) | ![stats_shown_with_dup](https://user-images.githubusercontent.com/904567/214362992-8ef2c05e-9d90-4f84-bbdb-8dfdf8bdae19.png) |

**Comment by drekdrek** [comment]
I've figured out why this was happening. I was negating something I shouldn't have. fix should be up soon

**Comment by drekdrek** [comment]
fixed in latest
