### ISSUE TITLE
Error Message in logs + lost hours

### ISSUE THREAD

**Issue by RCinCHgamer01** [drekdrek/grinding-stats#23]
![image](https://github.com/drekdrek/grinding-stats/assets/135046223/d14a8a55-52d8-4045-b069-fe64922f3202)
This is the error message that i am getting in the openplanet logs.
Also i lost over 1.2k hours without any, also on maps, that i even played on the same day. On all of the lost maps, it doesn't want to count anymore.
little comparison of what i had before and after: 
![image](https://github.com/drekdrek/grinding-stats/assets/135046223/8ea55a91-f541-49a9-8cef-c4e3dc49121b)
![image](https://github.com/drekdrek/grinding-stats/assets/135046223/cdae0bc4-3ccf-467f-b804-ced87d194beb)
you can see pretty good that there are some maps missing on the 2nd one. 
Thank you for any help/solution! :)  

Little update: seems like i was wrong about the lost maps not counting anymore. they still do. but they won't appear in the recap which is the main problem.

**Comment by Airwam** [comment]
I guess it's still more useful if I comment here since I have the same problem and maybe I have more info.
I get the exact same errors as [RCinCHgamer01](https://github.com/RCinCHgamer01) but when I do open grinding stats recap, it shows this : 
![image](https://github.com/drekdrek/grinding-stats/assets/59014002/b6ae8cfa-09ed-4318-805d-2d09fa9c4672)
however if I change categories, it shows more but still only ~260 maps max 
![image](https://github.com/drekdrek/grinding-stats/assets/59014002/969c5d07-6024-4319-90ff-c45fec850ddd)
this isnt at all coherent since in the folder with all the data there's like 3.3k files
![image](https://github.com/drekdrek/grinding-stats/assets/59014002/8f64fa12-5aac-4e31-8802-380c3ba8663a)

Already tried uninstalling and reinstalling the plugin, it did not work at all
Also, the plugin is still registering the data correctly since on every maps the little box seems correct and updates well.

hopefully this can help a bit to find a solution

**Comment by CatzHoekk** [comment]
Probably 1 corrupt file somewhere. Sure you don't get an error message that spits out a mapId/filename?

**Comment by Airwam** [comment]
![image](https://github.com/drekdrek/grinding-stats/assets/59014002/147373ef-ed81-4662-bfc8-86a72ee92124)
nope, not a single mapId or filename, and this is the exact same as  [RCinCHgamer01](https://github.com/RCinCHgamer01) got.

**Comment by Ostarius1** [comment]
I have the same issue, seems like my error message has 3 more lines on the end compared to your guys' though?
![image](https://github.com/drekdrek/grinding-stats/assets/139075527/70d05dba-2fe5-4353-a09f-3266d50c0307)

Mine wasn't showing anything when sorting by "all tracks" even after hitting refresh but when I clicked through a few of the other filters and clicked back to all tracks it shows some but definitely not all. And it only shows 8/25 of the current seasonal campaign (seemingly random ones)
![image](https://github.com/drekdrek/grinding-stats/assets/139075527/6220553e-3554-4e4e-8475-3ae312418a83)

It might be worth noting that I managed to get the 25 .json files associated with the current seasonal campaign in the GrindingStats folder and removed all others, and they all displayed fine
![image](https://github.com/drekdrek/grinding-stats/assets/139075527/06c6077c-9a42-4ee3-9614-68c50abbf8b4)

I've also tried deleting my entire OpenplanetNext folder and having it regenerate, and then only installing the grinding stats plugin and copy pasting my GrindingStats folder into it and it does the same thing

Also it says this when I switch the filter, idk if that's a problem
![image](https://github.com/drekdrek/grinding-stats/assets/139075527/dd0d8dfe-f390-4414-aa04-06b0a37e952e)

**Comment by CatzHoekk** [comment]
![image](https://github.com/drekdrek/grinding-stats/assets/69237200/a9506d71-d76b-4f5e-8de4-113a7ddb29a7)

You seem to have stuff in that folder that is not a expected json file. Remove that desktop folder or file or whatnot and you should be good. 

There should only be those ~30 random letter gibberish *.json files in that folder.

**Comment by Ostarius1** [comment]
The thing is, there's nothing else in the folder, and I get no results when I search "deskto", so idk why it's saying that. And I didn't get a screenshot of it but earlier when I was messing around with it and I only had 1 .json in the folder, it showed "deskto" as a track name in the grinding stats recap window, but again there was nothing in the folder, and I have the option to show hidden files turned on in windows

**Comment by drekdrek** [comment]
i believe i have a fix for this, but I'd like some data to test with, if anyone could zip up their `Grinding Stats` data folder and send it to me, that'd be great :D

**Comment by drekdrek** [comment]
from the test data that i have gotten this is fixed, and will be released to the plugin manager soon

**Comment by drekdrek** [comment]
the update is now on the plugin manager
