### ISSUE TITLE
Feature Request: Track List

### ISSUE THREAD

**Issue by minerop5000** [drekdrek/grinding-stats#24]
I would love a list of all tracks (probably in a settings tab) where I can see all tracks with the grinding-stats.

Additional:
- sort by column
- search by track name

Use case:
For example, I would like to have a list of all tracks of one campaign and see which track I haven't grinded that much (by time) and probably can improve easily.

**Comment by drekdrek** [comment]
I'm the plugins tab there is a toggle for `Grinding Stats Recap` which is exactly what you're looking for

**Comment by drekdrek** [comment]
there isn't a search feature but that will be implemented in the future
