### ISSUE TITLE
does not save time on map

### ISSUE THREAD

**Issue by Unused-Joker** [drekdrek/grinding-stats#27]
Everytime I am on a server, campaign or matchmaking, it never saves the time I have spent on the map and this is with the recently updated version from 2 months ago as well.

**Comment by drekdrek** [comment]
is this a specific map or any maps at all?

**Comment by Unused-Joker** [comment]
All maps

**Comment by drekdrek** [comment]
does the `Grinding Stats` folder exist in your Openplanet folder?

**Comment by Unused-Joker** [comment]
No it does not, and I am going to guess that's the reason why it won't save
any of the times. So would I just need to make a folder ?

**Comment by drekdrek** [comment]
Yeah try making a folder, ill look into why its not detecting the folder not existing

**Comment by drekdrek** [comment]
do you get any errors in console when it starts or tries to load a file?

**Comment by Unused-Joker** [comment]
I'm currently not home at the moment but the only error I remember seeing
on the screen was mania exchange

**Comment by Unused-Joker** [comment]
Want me to make a folder in OpenPlanet or the plugins folder in OpenPlanet?

**Comment by drekdrek** [comment]
make a `Grinding Stats` folder in `OpenplanetNext`On Sep 15, 2023 7:19 PM, Unused-Joker ***@***.***> wrote:
Want me to make a folder in OpenPlanet or the plugins folder in OpenPlanet?

**Comment by Unused-Joker** [comment]
i do not have a OpenPlanetNext folder

**Comment by drekdrek** [comment]
the Grinding Stats folder is located at 
`C:/Users/<username>/OpenplanetNext/Grinding Stats`
if this doesn't exist try creating it

**Comment by Unused-Joker** [comment]
Okay, lets see if that changes anything

**Comment by Unused-Joker** [comment]
I exited the map, went back in and it didnt save

also the only error that pops up on my screen is 

![image_2023-09-17_151504199](https://github.com/drekdrek/grinding-stats/assets/128867843/694294ad-254d-41cf-bd45-f51da7dc01b8)

**Comment by Unused-Joker** [comment]
I needed to change the permissions of my user folder and that fixed it 

c:\users\name\
^This folder
