### ISSUE TITLE
Recap crashed game TMT

### ISSUE THREAD

**Issue by twiikker** [drekdrek/grinding-stats#29]
When opening recap game crashes.

Trackmania Turbo

[           Debug] [10:57:20] [GrindingStats]  Assertion failed: '"p >= Data && p < DataEnd"'
[           Debug] [10:57:20] [GrindingStats]  Assertion failed: '"idx >= 0 && idx < _Count"'

**Comment by drekdrek** [comment]
sorry for the delay, i have figured out the issue and and submitting it to the plugin manager, it should be out in a bit 😄
