### ISSUE TITLE
Standing respawn increments number of respawns by two

### ISSUE THREAD

**Issue by henrysallandt** [drekdrek/grinding-stats#39]
A flying respawn increments the number of respawns by one (intended behavior).
A standing respawn (press two times respawn button in quick succession) increments the number of respawns by two.

Could be fixed in a relatively stupid way (did not find a better method :D) using Time::get_Now().
1. initialise a variable with Time::get_Now() (when plugin is loaded)
2. When respawn is requested, check if Time::get_Now() - variable is lower than 1000 (--> 1sec) and only treat as another respawn is it is higher than that
3. set variable again to Time::get_Now()

**Comment by drekdrek** [comment]
this is just because you can initiate a standing respawn.
the double press of the respawn key
or a single press of the standing respawn keybind (unbound by default)

i'll look into any better methods for this

**Comment by drekdrek** [comment]
i got something working
https://github.com/drekdrek/grinding-stats/assets/35672537/c7c77591-60d0-4e1d-a87a-944ba3a8d5d0
