### ISSUE TITLE
Exporting data to be used as a dependency

### ISSUE THREAD

**Issue by FabianvZ** [drekdrek/grinding-stats#40]
Lokulicious and I have created our own plugin Discord Rivalry Ping. https://openplanet.dev/plugin/discordrivalryping. This plugin sends a message via a discord webhook when you beat your clubmates. We also send the grinding stats in this message. Currently we are running the grinding stats plugin within our plugin, but we would like to be able to use your plugin as a dependency. The data we use are the session and total stats for time, resets and respawns. It would also be nice if the Timer::to_string() method could be exported since we use this as well.

**Comment by drekdrek** [comment]
I've been thinking about this as I've been working on my big update/rewrite. I'm currently stuck trying to optimize recap, as it crashes when you load too many files.

I'll take a look at exposing as much data as possible as efficiently as possible.

**Comment by FabianvZ** [comment]
I noticed the recent update and wanted to follow up on this feature request. I’m curious if there are any plans to implement it, and if possible, could you share when or if I might expect it to be included?

**Comment by drekdrek** [comment]
i do have plans to implement this.
i was in a rush to get this update out before the campaign

**Comment by drekdrek** [comment]
currently i am going to expose these stats:
- total and session time
- total and session finishes
- total and session attempts
- total, session and current respawns,
- time to string, both with and without thousandths place

is there any other things you think you would need?
