### ISSUE TITLE
Recap not showing some tracks

### ISSUE THREAD

**Issue by kr4lll** [drekdrek/grinding-stats#45]
the recap doesnt show some tracks e.g. (played track 1-15 but recap only show 2,3,6,10,13) i individually go to each track and can see the grinding stats windows displaying the time on it.

**Comment by drekdrek** [comment]
how many files are you loading for your recap? i'll be getting an update out today that will make it load more than 500 files

**Comment by drekdrek** [comment]
this should be fixed now
