### ISSUE TITLE
Plugin adds one finish when opening a map on MP4

### ISSUE THREAD

**Issue by Fort-TM** [drekdrek/grinding-stats#51]
## Issue

When opening a map on Trackmania 2 / MP4, the plugin will add a finish to the session total when loading a map, despite not starting a run

## Image
![228760_551](https://github.com/user-attachments/assets/09282c05-2057-494b-a8df-2a5a0f71a143)

## Explanation

When you open a map, MP4 seems to set ScriptAPI.RaceState to CTrackManiaPlayer::ERaceState::Finished for some reason, which can be confirmed by printing RaceState on the console

```
[   ScriptRuntime] [  LOG] [17:25:09] [GrindingStats]  Read finishes 11 resets 25 time 542476 respawns 0
# not including JSON since it's useless here
[   ScriptRuntime] [  LOG] [17:25:09] [GrindingStats]  Finished
[   ScriptRuntime] [  LOG] [17:25:11] [GrindingStats]  BeforeStart
[   ScriptRuntime] [  LOG] [17:25:16] [GrindingStats]  Running
```

**Comment by drekdrek** [comment]
fixed in cd4f211
