### ISSUE TITLE
Show hour on Total time and Session Time even when it is 0

### ISSUE THREAD

**Issue by MacGaitas** [drekdrek/grinding-stats#8]
Hi, this is just something that used to be configurable but I think it got removed. I lock my grinding stats in the right corner of the screen and since the hours don't show up when it is under 00 I can't fit it correctly to the edge of the screen because the witdh is lower than is usually is when the hours is >= 1.
As another alternative you could also provide ways for us to manually configure the width and height of the window but since I believe that's more complicated I would be grateful if the "Show hour when 0" made its way back into the plugin (which is a great one btw!)

Regarding whether you choose to update it or not thanks for you time and work! 🙌

**Comment by drekdrek** [comment]
weird, I'll take a look at that. I don't remember removing anything...

**Comment by MacGaitas** [comment]
Thanks for the fast response!
I took a peak into the code and in the last commit I believe you may accidentally left that logic out.
![image](https://user-images.githubusercontent.com/43335889/163291205-d0213748-32ec-412f-809e-c9854131700e.png)

**Comment by drekdrek** [comment]
fixed in 0407a13
I still don't remember removing this, maybe I was half asleep.

it'll be on the plugin manager soon

**Comment by MacGaitas** [comment]
Thanks, appreciate it a lot!

**Comment by drekdrek** [comment]
up on the manager!
