### ISSUE TITLE
Show Recap by Map/Campain without having to load each map

### ISSUE THREAD

**Issue by ChristopheCVB** [drekdrek/grinding-stats#9]
Right now to be able to see how much time we spent in a map, we have to load it.
Would be cool to have a Recap UI that we could open, detailing each map. Same for campains would be a bonus ;)

Thank you for your hard work ;)

**Comment by drekdrek** [comment]
this is something I've wanted to do for a while now.

I'll get to work on this in a few days after final exams are done for the semester!

**Comment by drekdrek** [comment]
its been a bit of time but...
![image](https://drek.cc/i/raw/4IEsZlLC.png)
its all coming together

**Comment by drekdrek** [comment]
added in b7a8c522143bf80fcb1313d69afb49ad75f456d1
will be released soon
